name: Deploy to GitHub Pages

on:
  # Ejecutar cuando hay un push a la rama main
  push:
    branches: [ main ]
  # Permite ejecutar este workflow manualmente desde la pestaña Actions en GitHub
  workflow_dispatch:

# Permite clonar el repositorio y desplegar a GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Solo permite una implementación simultánea, saltando ejecutar en cola
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Instalar Bun en el runner
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Cachear Bun (si hay bun.lock o package.json)
        uses: actions/cache@v4
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock','package.json') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Instalar dependencias con Bun
        run: bun install

      - name: Construir sitio con Bun
        run: bun run build

      - name: Subir artefactos para despliegue
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4